### ISSUE TITLE
Logs 2

### ISSUE THREAD

**Issue by silverdrake11** [silverdrake11/covid_rates_per_capita#5]

**Comment by silverdrake11** [comment]
MS,0
OH,0
NC,0

**Comment by silverdrake11** [comment]
IA,confirmed,62,30707

**Comment by silverdrake11** [comment]
CT,confirmed,38,153

**Comment by silverdrake11** [comment]
Traceback (most recent call last):
  File "/root/covid8/frames.py", line 77, in get_most_recent_df
    df = df.append(data.get_john_hopkins_df())
  File "/root/covid8/data.py", line 110, in get_john_hopkins_df
    if row[1] == 'US':
IndexError: list index out of range

**Comment by silverdrake11** [comment]
Traceback (most recent call last):
  File "/root/covid8/frames.py", line 77, in get_most_recent_df
    df = df.append(data.get_john_hopkins_df())
  File "/root/covid8/data.py", line 110, in get_john_hopkins_df
    if row[1] == 'US':
IndexError: list index out of range

**Comment by silverdrake11** [comment]
Traceback (most recent call last):
  File "/root/covid8/frames.py", line 77, in get_most_recent_df
    df = df.append(data.get_john_hopkins_df())
  File "/root/covid8/data.py", line 110, in get_john_hopkins_df
    if row[1] == 'US':
IndexError: list index out of range

**Comment by silverdrake11** [comment]
ND,0
OR,0
AL,0
NY,0
MT,0
WI,0
CO,0
PA,0
KS,0
AK,0
MO,0
OK,0
TX,0

**Comment by silverdrake11** [comment]
IA,confirmed,69,30744

**Comment by silverdrake11** [comment]
IL,confirmed,248,4049

**Comment by silverdrake11** [comment]
NC,0
Traceback (most recent call last):
  File "/root/covid8/frames.py", line 77, in get_most_recent_df
    df = df.append(data.get_john_hopkins_df())
  File "/root/covid8/data.py", line 110, in get_john_hopkins_df
    if row[1] == 'US':
IndexError: list index out of range

**Comment by silverdrake11** [comment]
ID,confirmed,13,76
Traceback (most recent call last):
  File "/root/covid8/frames.py", line 77, in get_most_recent_df
    df = df.append(data.get_john_hopkins_df())
  File "/root/covid8/data.py", line 110, in get_john_hopkins_df
    if row[1] == 'US':
IndexError: list index out of range

**Comment by silverdrake11** [comment]
ID,confirmed,13,81
Traceback (most recent call last):
  File "/root/covid8/frames.py", line 77, in get_most_recent_df
    df = df.append(data.get_john_hopkins_df())
  File "/root/covid8/data.py", line 110, in get_john_hopkins_df
    if row[1] == 'US':
IndexError: list index out of range

**Comment by silverdrake11** [comment]
Traceback (most recent call last):
  File "/root/covid8/frames.py", line 77, in get_most_recent_df
    df = df.append(data.get_john_hopkins_df())
  File "/root/covid8/data.py", line 110, in get_john_hopkins_df
    if row[1] == 'US':
IndexError: list index out of range

**Comment by silverdrake11** [comment]
WA,deaths,8,43

**Comment by silverdrake11** [comment]
NE,0
GU,0
MD,0
MN,0
FL,0
TN,0

**Comment by silverdrake11** [comment]
IA,confirmed,67,30749

**Comment by silverdrake11** [comment]
Traceback (most recent call last):
  File "/root/covid8/frames.py", line 77, in get_most_recent_df
    df = df.append(data.get_john_hopkins_df())
  File "/root/covid8/data.py", line 110, in get_john_hopkins_df
    if row[1] == 'US':
IndexError: list index out of range

**Comment by silverdrake11** [comment]
Traceback (most recent call last):
  File "/root/covid8/frames.py", line 77, in get_most_recent_df
    df = df.append(data.get_john_hopkins_df())
  File "/root/covid8/data.py", line 110, in get_john_hopkins_df
    if row[1] == 'US':
IndexError: list index out of range

**Comment by silverdrake11** [comment]
MT,0
DC,0
VI,0
CT,0
AR,0
SD,0
OK,0
KY,0
WV,0
NM,0
MI,0
OH,0
MS,0
IL,0
NC,0
WI,0
LA,0
IN,0
SC,0
ID,0
NH,0
AL,0
VT,0
RI,0
WA,0
NV,0

**Comment by silverdrake11** [comment]
IA,confirmed,75,30746

**Comment by silverdrake11** [comment]
Traceback (most recent call last):
  File "/root/covid8/frames.py", line 77, in get_most_recent_df
    df = df.append(data.get_john_hopkins_df())
  File "/root/covid8/data.py", line 110, in get_john_hopkins_df
    if row[1] == 'US':
IndexError: list index out of range

**Comment by silverdrake11** [comment]
Traceback (most recent call last):
  File "/root/covid8/frames.py", line 77, in get_most_recent_df
    df = df.append(data.get_john_hopkins_df())
  File "/root/covid8/data.py", line 110, in get_john_hopkins_df
    if row[1] == 'US':
IndexError: list index out of range

**Comment by silverdrake11** [comment]
Traceback (most recent call last):
  File "/root/covid8/frames.py", line 77, in get_most_recent_df
    df = df.append(data.get_john_hopkins_df())
  File "/root/covid8/data.py", line 110, in get_john_hopkins_df
    if row[1] == 'US':
IndexError: list index out of range

**Comment by silverdrake11** [comment]
VA,-5
VA,-231
AZ,0
GA,0
FL,0
MO,0
TN,0

**Comment by silverdrake11** [comment]
Traceback (most recent call last):
  File "/root/covid8/frames.py", line 77, in get_most_recent_df
    df = df.append(data.get_john_hopkins_df())
  File "/root/covid8/data.py", line 110, in get_john_hopkins_df
    if row[1] == 'US':
IndexError: list index out of range

WA,0

**Comment by silverdrake11** [comment]
Traceback (most recent call last):
  File "/root/covid8/frames.py", line 77, in get_most_recent_df
    df = df.append(data.get_john_hopkins_df())
  File "/root/covid8/data.py", line 110, in get_john_hopkins_df
    if row[1] == 'US':
IndexError: list index out of range

**Comment by silverdrake11** [comment]
Traceback (most recent call last):
  File "/root/covid8/frames.py", line 77, in get_most_recent_df
    df = df.append(data.get_john_hopkins_df())
  File "/root/covid8/data.py", line 110, in get_john_hopkins_df
    if row[1] == 'US':
IndexError: list index out of range

**Comment by silverdrake11** [comment]
Traceback (most recent call last):
  File "/root/covid8/frames.py", line 77, in get_most_recent_df
    df = df.append(data.get_john_hopkins_df())
  File "/root/covid8/data.py", line 110, in get_john_hopkins_df
    if row[1] == 'US':
IndexError: list index out of range

**Comment by silverdrake11** [comment]
WA,confirmed,63,570

**Comment by silverdrake11** [comment]
MN,0
GU,0

**Comment by silverdrake11** [comment]
IA,confirmed,103,30768
IL,confirmed,747,4000

**Comment by silverdrake11** [comment]
AZ,0
Traceback (most recent call last):
  File "/root/covid8/frames.py", line 77, in get_most_recent_df
    df = df.append(data.get_john_hopkins_df())
  File "/root/covid8/data.py", line 110, in get_john_hopkins_df
    if row[1] == 'US':
IndexError: list index out of range

**Comment by silverdrake11** [comment]
Traceback (most recent call last):
  File "/root/covid8/frames.py", line 77, in get_most_recent_df
    df = df.append(data.get_john_hopkins_df())
  File "/root/covid8/data.py", line 110, in get_john_hopkins_df
    if row[1] == 'US':
IndexError: list index out of range

**Comment by silverdrake11** [comment]
Traceback (most recent call last):
  File "/root/covid8/frames.py", line 77, in get_most_recent_df
    df = df.append(data.get_john_hopkins_df())
  File "/root/covid8/data.py", line 110, in get_john_hopkins_df
    if row[1] == 'US':
IndexError: list index out of range

**Comment by silverdrake11** [comment]
Traceback (most recent call last):
  File "/root/covid8/frames.py", line 77, in get_most_recent_df
    df = df.append(data.get_john_hopkins_df())
  File "/root/covid8/data.py", line 110, in get_john_hopkins_df
    if row[1] == 'US':
IndexError: list index out of range

**Comment by silverdrake11** [comment]
TN,0
AL,0
IL,0

**Comment by silverdrake11** [comment]
IA,confirmed,102,30824

**Comment by silverdrake11** [comment]
Traceback (most recent call last):
  File "/root/covid8/frames.py", line 77, in get_most_recent_df
    df = df.append(data.get_john_hopkins_df())
  File "/root/covid8/data.py", line 110, in get_john_hopkins_df
    if row[1] == 'US':
IndexError: list index out of range

**Comment by silverdrake11** [comment]
Traceback (most recent call last):
  File "/root/covid8/frames.py", line 77, in get_most_recent_df
    df = df.append(data.get_john_hopkins_df())
  File "/root/covid8/data.py", line 110, in get_john_hopkins_df
    if row[1] == 'US':
IndexError: list index out of range

**Comment by silverdrake11** [comment]
Traceback (most recent call last):
  File "/root/covid8/frames.py", line 77, in get_most_recent_df
    df = df.append(data.get_john_hopkins_df())
  File "/root/covid8/data.py", line 110, in get_john_hopkins_df
    if row[1] == 'US':
IndexError: list index out of range

**Comment by silverdrake11** [comment]
Traceback (most recent call last):
  File "/root/covid8/frames.py", line 77, in get_most_recent_df
    df = df.append(data.get_john_hopkins_df())
  File "/root/covid8/data.py", line 110, in get_john_hopkins_df
    if row[1] == 'US':
IndexError: list index out of range
